name: flutter_web_integration_test
description: Chrome WebDriver integration test framework for Dart web applications
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  webdriver: ^3.0.2
  http: ^1.1.0
  path: ^1.8.3
  yaml: ^3.1.2
  glob: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  integration_test:
    sdk: flutter

flutter:

executables:
  flutter_web_integration_test:
